initial = '''\t +--------+\n\t        | |\n\t        | |\n\t        | |\n\t +--------+'''
first_mistake = '''\t +--------+\n\t  0     | |\n\t        | |\n\t        | |\n\t +--------+'''
second_mistake = '''\t +--------+\n\t  0     | |\n\t /       | |\n\t        | |\n\t +--------+'''
third_mistake = '''\t +--------+\n\t  0     | |\n\t /|      | |\n\t        | |\n\t +--------+'''
fourth_mistake = '''\t +--------+\n\t  0     | |\n\t /|\      | |\n\t        | |\n\t +--------+'''
fifth_mistake = '''\t +--------+\n\t  0     | |\n\t /|\     | |\n\t /       | |\n\t +--------+'''
six_mistake = '''\t +--------+\n\t  0     | |\n\t /|\      | |\n\t / \    | |\n\t +--------+'''
